
-- Create report for the new brands from vendors.

--||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
--USE [DataBase]
--SELECT A.VendorId
--	  ,MAX(A.vendor) AS VendorName
--	  ,COUNT(*) AS QtyOFOrders
--FROM [vsql3\instance3].[CRmAPTools].dbo.VW_OrderItemsWithPOs AS A
--JOIN [vsql1\instance1].[DataBase].dbo.Vendor AS B ON B.Id = A.VendorId
--WHERE A.OrderDate >= '2023-01-01' AND A.VendorID IS NOT NULL AND A.VendorId <> 295 AND B.Active = 1
--GROUP BY A.vendorid-- , MONTH(CAST(a.OrderDate as date))
--ORDER BY QtyOFOrders DESC

USE Vendordata
SELECT VendorId,CAST('PartsAuthority' AS nvarchar(50)) AS Vendor,QtyBrands INTO #20FirstBrands FROM (SELECT 125 AS VendorId, COUNT(DISTINCT A.Brand_Name) AS QtyBrands FROM Inventory_PartsAuthority  AS A WITH (NOLOCK) LEFT JOIN [vsql4\instance4].[Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid IN (125,180)  AND B.VendorManCode = A.Linecode WHERE B.id IS NULL AND A.Linecode NOT IN('X3','UX','X4','X6','7X') ) AS B GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Land And Sea' AS Vendor,QtyBrands  FROM (SELECT 191 AS VendorId, COUNT(DISTINCT A.[MAJOR PRODUCT CODE]) AS QtyBrands FROM Inventory_LandAndSea AS A WITH (NOLOCK) LEFT JOIN [vsql4\instance4].[Autoplicity].[dbo].[PriceSheet] AS B  WITH (NOLOCK) ON B.VendorManCode = LTRIM(RTRIM(A.[MAJOR PRODUCT CODE])) AND VendorId = 191 WHERE B.id IS NULL AND A.[AVAIL INV Y/N    1]='Y' AND A.[AVAIL INV Y/N    2]='Y' AND A.[AVAIL INV Y/N    3]='Y' AND A.[AVAIL INV Y/N    4]='Y' AND A.[AVAIL INV Y/N    5]='Y' AND A.[AVAIL INV Y/N    6]='Y' AND A.[AVAIL INV Y/N    7]='Y' AND A.[AVAIL INV Y/N    8]='Y' AND A.[AVAIL INV Y/N    9]='Y' AND A.[AVAIL INV Y/N    11]='Y' AND A.[AVAIL INV Y/N    12]='Y' AND A.[AVAIL INV Y/N    13]='Y' AND A.[AVAIL INV Y/N    14]='Y' AND A.[AVAIL INV Y/N    15]='Y' ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Meyer Distributing' AS Vendor,QtyBrands  FROM (SELECT 90 AS VendorId, COUNT(DISTINCT LEFT(A.VendorPartNumber, 3)) AS QtyBrands FROM Inventory_meyer AS A WITH (NOLOCK) LEFT JOIN [vsql4\instance4].[Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 90 and B.VendorManCode=LEFT(A.VendorPartNumber, 3) WHERE B.id IS NULL AND A.StockQTY > 0 AND A.MfgQTY > 0 ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'FMPco' AS Vendor,QtyBrands  FROM (SELECT 190 AS VendorId, COUNT(DISTINCT A.Line) AS QtyBrands FROM Inventory_fmpco AS A WITH (NOLOCK) LEFT JOIN [vsql4\instance4].[Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 190 AND B.VendorManCode = A.Line WHERE B.id IS NULL AND A.Line NOT IN('BNG','CNT','MED','WWD','CCE','DGA','MAR','RVC','MSL','PLA','EGD','FRE','AP5','TRS')) AS A GROUP BY VendorId,QtyBrands ;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Turn14' AS Vendor,QtyBrands  FROM (SELECT 11 AS VendorId, COUNT(DISTINCT A.PrimaryVendor) AS QtyBrands FROM Inventory_Turn14 AS A WITH (NOLOCK) LEFT JOIN [vsql4\instance4].[Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.VendorId = 11 AND  B.VendorBrandName = A.PrimaryVendor WHERE B.id IS NULL AND A.PrimaryVendor NOT IN('OMIX','Rugged Ridge','Undercover','Truxedo','BAK','BackRack','Roll-N-Lock','Poison Spyder','Pivot Works','Hot Cams','Cylinder Works','All Balls Racing')) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Keystone' AS Vendor,QtyBrands  FROM (SELECT 5 AS VendorId, COUNT(DISTINCT A.VendorName) AS QtyBrands FROM Inventory_keystone AS A WITH (NOLOCK) LEFT JOIN [vsql4\instance4].[Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.VendorManCode = A.VenCode AND B.VendorId = 5 WHERE B.id IS NULL AND A.VendorName NOT IN('SEAWIDE CATC','ACLIM8','PREPAIDFRT') ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'SimpleTire Wholesale' AS Vendor,QtyBrands  FROM (SELECT 292 AS VendorId, COUNT(DISTINCT C.Brand) AS QtyBrands FROM [vsql4\instance4].vendordata.[dbo].Inventory_SimpleTire_APIInventory AS A WITH (NOLOCK) JOIN [vsql4\instance4].vendordata.[dbo].Inventory_SimpleTire_Inventory AS B WITH (NOLOCK) ON B.ProductID = A.ProductID JOIN [vsql4\instance4].vendordata.[dbo].Inventory_SimpleTire_ProductData AS C WITH (NOLOCK) ON C.ProductID = A.ProductID  LEFT JOIN [vsql4\instance4].[Autoplicity].[dbo].[PriceSheet] AS D WITH (NOLOCK) ON D.Vendorid = 292 AND D.VendorBrandName = C.Brand WHERE D.id IS NULL AND A.Quantity > 0 AND B.Quantity > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Midstate Tool & Supply' AS Vendor,QtyBrands  FROM (SELECT 379 AS VendorId, COUNT(DISTINCT A.Brand) AS QtyBrands FROM Inventory_Midstate AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.VendorId = 379 AND  B.VendorBrandName = A.Brand WHERE B.id IS NULL AND A.Brand NOT IN ('KLEIN TOOLS INC','CLORE AUTOMOTIVE','H & S AUTOSHOT LLC','WCTA / WELDING,CUTTING,TOOLS&ACCESS,LLC','LENCO / NLC INC','PORTER FERGUSON/LOWELL CORPORATION','AIR FILTRATION CO INC','SCHUMACHER ELECTRIC CORP','SPG-INTERNATIONAL LTEE','WATERLOO','CEQUENT CONSUMER PRODUCTS','WHEEL-A-MATIC, LLC*OFFICIALLY CLOSED','FERRO INDUSTRIES INC','NORTH SHORE HOLDINGS LLC/SAFETY SEAL','RAYOVAC - SPECTRUM BRANDS','PLASTI DIP INTERNATIONAL','SPARTAN PLASTICS','PITTSBURGH SPRAY EQUIP','DEWITT GROUP','HUGHES-PETERS INC','UNITED STATES CAN CO','MDS INC','HORNELL SPEEDGLAS','I T & T INC-no longer in business 2/''07','W I SERVICE PARTS','SCI / TIPS','OK SPARK USA INC','ORS NASCO','WHEEL PRODUCTS BY MCCOURT')) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Integrated Supply Network' AS Vendor,QtyBrands  FROM (SELECT 150 AS VendorId, COUNT(DISTINCT A.Brand) AS QtyBrands FROM Inventory_ISN_New AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 150 AND B.VendorBrandName = A.Brand WHERE B.id IS NULL AND A.Brand NOT IN('','PULSAR PRODUCTS INC','Belaire','Havalon Knives','FAKE','LEE JAMES FLORAL','Schumacher','R.E.L. Products','Fake Suplier') ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'WorldPac' AS Vendor,QtyBrands FROM (SELECT 93 AS VendorId, COUNT(DISTINCT [WORLDPAC Brand Description]) AS QtyBrands FROM Inventory_WorldPac AS A WITH (NOLOCK) LEFT JOIN [vsql4\instance4].[Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 93 AND B.VendorBrandName = A.[WORLDPAC Brand Description] WHERE B.id IS NULL AND A.[WORLDPAC Brand Description] NOT IN('HRM','Gloveworks','TJM Products','DYK Automotive','Coca-Cola','Flowmaster','Integrated Supply Network','M. Eagles Tool Warehouse Inc.','Edelbrock','German Sensor Tech','''','Tru-Flate','Auto Ventshade','Curt Towing','Spectre','Ken Tool','MSD','Smith & Wesson','Premium Guard','Access Tools','S & G Tool Aid','EastPenn','Clip Light','Custom Leathercraft','Bahama Bag','B&M','H&S Autoshot','','DOM')) AS A ;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Motorstate' AS Vendor,QtyBrands  FROM (SELECT 39 AS VendorId, COUNT(DISTINCT A.Brand) AS QtyBrands FROM Inventory_Motorstate AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.VendorId = 39 AND  B.VendorBrandName = A.Brand WHERE B.id IS NULL AND A.Brand NOT IN ('B M PERFORMANCE','AEM ELECTRONICS','Motorstate Catalog','DEWITTS RADIATOR','SuperSprings International','MALLORY','POINT ONE','MONIT','''','EXTREME RACING OIL')) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Turn14-DS' AS Vendor,QtyBrands  FROM (SELECT 314 AS VendorId, COUNT(DISTINCT B.brand) AS QtyBrands FROM Inventory_Turn14Api_Inventory AS A WITH (NOLOCK) JOIN [Inventory_Turn14Api_Items] AS B WITH (NOLOCK) ON B.Id = A.ID JOIN Inventory_Turn14Api_Prices AS C WITH (NOLOCK) ON C.Id = B.Id LEFT JOIN Inventory_Turn14 AS D WITH (NOLOCK) ON D.InternalPartNumber = B.part_number LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS E WITH (NOLOCK) ON E.VendorId = 314 AND  E.VendorBrandName = B.brand WHERE E.id IS NULL AND B.active='True' AND ISNULL(B.dropship_controller_id,0)<>0 AND B.brand NOT IN('OMIX','Rugged Ridge','Undercover','Truxedo','BAK','BackRack','Roll-N-Lock','Poison Spyder') ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Auto Plus' AS Vendor,QtyBrands  FROM (SELECT 170 AS VendorId, COUNT(DISTINCT A.linecode) AS QtyBrands FROM Inventory_Uniselect AS A LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B ON B.Vendorid = 170 and B.VendorManCode = A.linecode WHERE B.id IS NULL AND (A.[Branch290QOH] + A.[Branch295QOH]) > 0 AND A.LineCodeDescription NOT IN ('EDELBROCK CORP.','Edelbrock Corporation','IMPORT PRODUCTS COMPANY','ENSURE WHEEL-CHINA (IMPORT)','FRICTION MATERIALS GROUP NA','PLASTI DIP INTERNATIONAL','COCA COLA PRODUCTS','Pulsar Products inc','SCEPTER MFG. CO. LTD.','B&M Automotive Prod. (WSO)','RAMPAGE PRODUCTS LLC (3SR)','FGX INTERNATIONAL','CAP AMERICA','FLOWMASTER INC. (3SR)','PBY MERCHANDISE -USED BATTERY','TIRECO INC','SECURITY EQUIPMENT CORP','A.P. 51 LLC -Jay Lenos Garage','DELMAR CENGAGE LEARNING','UNBREAKABLE UNLIMITED CO.','Cobra Electronics Corporation','JVC MOBILE CO OF AMERICA','M. Block and Bon INC.','META-COG','RAMPS-STANDS','Brake Shoe Kits','GARMIN INTERNATIONAL','BRAVO SPORTS (FRMLY VARIFLEX)','CUSTOM LEATHERCRAFT','COMPUTER SPECIALTY PRODUCTS','SBC BUYOUT','PLASTICAL INDUSTRIES','BNM','PULSAR PRODUCTS','B&M')) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Premier Performance' AS Vendor,QtyBrands  FROM (SELECT 36 AS VendorId, COUNT(DISTINCT A.[line code]) AS QtyBrands FROM Inventory_PremierNew AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 36 and B.VendorManCode = A.[line code] WHERE B.id IS NULL AND A.Brand NOT IN('SAA','Mav Fab','AP Racing','FUNCTION AND FORM','SuperStik','PLANTED','Escort','ML24','HOA','Ammex','Permaseal','Fortune Auto','RSP','KIC','BINH TRAN','Daytime Bright Lights','Getta Grip','[DANGEROUS!]Extang','JB Manufacturing','Honda/Acura OEM','KW SPECIALTY','Custom Performance Engineering','Honda/Acura OEM Niel huffman','Valenti','Planted Technologies','Got Your Six Coffee Co.','Walker','Extang','Gator Fasteners')) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Vision Wheel' AS Vendor,QtyBrands  FROM (SELECT 382 AS VendorId, COUNT(DISTINCT A.Brand) AS QtyBrands FROM Inventory_VisionWheels AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.VendorId = 382 AND  B.VendorBrandName = A.Brand WHERE B.id IS NULL ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'LorenzJones' AS Vendor,QtyBrands  FROM (SELECT 289 AS VendorId, COUNT(DISTINCT A.Notes) AS QtyBrands FROM Inventory_LorenzJonesAInventory AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.VendorId = 289 AND  B.VendorBrandName = A.Notes WHERE B.id IS NULL AND A.Notes NOT IN('DONOVAN MARINE INC','ITI CO., LTD','LIPPERT-DO NOT USE')) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'ATD' AS Vendor,QtyBrands  FROM (SELECT 311 AS VendorId, COUNT(DISTINCT A.BrandName) AS QtyBrands FROM Inventory_ATD_FileApiData AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.VendorId = 311 AND B.VendorBrandName = A.BrandName WHERE B.id IS NULL AND A.QuantityAvailable > 0 AND A.BrandName NOT IN('CIMS','Group 31','Privat','Ultra CRT','SU01','Trade Union','Suspension')) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'APW - DS' AS Vendor,QtyBrands  FROM (SELECT 218 AS VendorId, COUNT(DISTINCT A.VendorName) AS QtyBrands FROM Inventory_APWKnoxSeeman AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.VendorId = 218 AND B.VendorBrandName = A.VendorName WHERE B.id IS NULL AND A.QTYAvail > 0 AND A.VendorName NOT IN('','K&N Filters')) AS A GROUP BY VendorId,QtyBrands ;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Eagle Tools' AS Vendor,QtyBrands  FROM (SELECT 396 AS VendorId, COUNT(DISTINCT A.Brand) AS QtyBrands FROM Inventory_EagleTools AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.VendorId = 396 AND B.VendorBrandName = A.Brand WHERE B.id IS NULL AND A.Brand NOT IN ('DISCONTINUED','GRIP-ON-TOOLS','H & S AUTOSHOT DO NOT USE','METW CLORE ACCOUNT - ACH','Clore Automotive','DELEATED','NO LONGER IN USE')) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'ORS Nasco' AS Vendor,QtyBrands  FROM (SELECT 386 AS VendorId, COUNT(DISTINCT LEFT(A.VendorPartNumber, 3)) AS QtyBrands FROM Inventory_ORS AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.VendorId = 386 AND B.VendorManCode = LEFT(A.VendorPartNumber, 3) WHERE B.id IS NULL AND LEFT(A.VendorPartNumber,3) NOT IN ('898','409','562','777','380','201','620','676','197','298','001','471','827','050','480','TXL','998','023','517') ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'XL Parts' AS Vendor,QtyBrands  FROM (SELECT 395 AS VendorId, COUNT(DISTINCT A.Line) AS QtyBrands FROM Inventory_XLParts AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.VendorId = 395 AND B.VendorManCode = A.Line WHERE B.id IS NULL AND A.Line NOT IN('XLP','ROV')) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Competition Specialties' AS Vendor,QtyBrands  FROM (SELECT 35 AS VendorId, COUNT(DISTINCT A.VendorManCode) AS QtyBrands FROM Inventory_CompSpec AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.VendorManCode = A.VendorManCode AND B.VendorId = 35  WHERE B.id IS NULL ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'APW Knox-Seeman' AS Vendor,QtyBrands  FROM (SELECT 139 AS VendorId, COUNT(DISTINCT A.VendorName) AS QtyBrands FROM Inventory_APWKnoxSeeman AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 139 AND B.VendorBrandName = A.VendorName  WHERE B.id IS NULL AND A.QTYAvail > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Earl Owen Company' AS Vendor,QtyBrands  FROM (SELECT 363 AS VendorId, COUNT(DISTINCT B.brand) AS QtyBrands FROM Inventory_EarlOwen AS A WITH (NOLOCK) LEFT JOIN Inventory_EarlOwen_MasterData AS B WITH (NOLOCK) ON B.Code = A.brand LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS C WITH (NOLOCK) ON C.VendorBrandName = B.brand AND C.VendorId = 363 WHERE C.id IS NULL AND A.brand NOT IN('LUN','OMX','RGR','WHP','AVS','STA','NFA','AIR','EXT','HYP','UND','BAK','BUS','RET','AEM','TRX','RUG','NSP','UWS','RAM','RNL','CLA','AMP','CAW','BDR','SEM','BAC','ROA','ZBR','SCS','FED','DSC','LIP','KID','SCO','ATZ','ORF','CRL','DES','TRY','GNV','RYA','SEA','HAN')) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'The Parts House' AS Vendor,QtyBrands  FROM (SELECT 341 AS VendorId, COUNT(DISTINCT A.Line_code) AS QtyBrands FROM Inventory_ThePartsHouse AS A WITH (NOLOCK) LEFT JOIN Gena_THP_LineCode AS B WITH (NOLOCK) ON B.new = A.Line_code LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS C WITH (NOLOCK) ON C.VendorManCode = A.Line_code AND C.VendorId = 341  WHERE C.id IS NULL AND  AND A.Line_code NOT IN ('SGR','SHR','ART','GPN','IDC','GLK','PCA','VES','KNE','FIS','RPC','BMA','PHP') AND ISNULL(A.Stock_2001, 0) + ISNULL(A.Stock_2040, 0)> 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Advance Tire Wholesale' AS Vendor,QtyBrands  FROM (SELECT 307 AS VendorId, COUNT(DISTINCT A.mfg) AS QtyBrands 	FROM Inventory_advanceTire AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 307 and B.VendorBrandName = A.mfg WHERE B.ID IS NULL AND  A.Avail > 0 AND A.Mfg NOT IN('','Tiber','Tacoma','Suretrac')) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'SSF Auto Parts' AS Vendor,QtyBrands  FROM (SELECT 202 AS VendorId, COUNT(DISTINCT A.[Mfg Name]) AS QtyBrands 	FROM Inventory_SSF AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 202 and B.VendorBrandName = A.[Mfg Name] WHERE B.ID IS NULL AND A.[Mfg Name] NOT IN ('CASCO','RAYOVAC HIGH ENERGY','ENERGIZER','VEGAZ','RAYOVAC FUSION','DISTILLED WATER','')) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'3DMaxPider' AS Vendor,QtyBrands  FROM (SELECT 367 AS VendorId, COUNT(DISTINCT LEFT(A.MPN,2)) AS QtyBrands 	FROM Inventory_3DMaxPider AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 367 and B.VendorManCode = LEFT(A.MPN,2) WHERE B.ID IS NULL) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'CWR Electronics' AS Vendor,QtyBrands  FROM (SELECT 228 AS VendorId, COUNT(DISTINCT A.ManufacturerName) AS QtyBrands 	FROM Inventory_CWRElectronics_Catalog AS A WITH (NOLOCK) LEFT JOIN [vsql4\instance4].[Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 228 and B.VendorBrandName = A.ManufacturerName WHERE B.ID IS NULL AND A.ManufacturerName NOT IN ('CRAFTSMAN','CURT')) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Tucker Rocky' AS Vendor,QtyBrands  FROM (SELECT 185 AS VendorId, COUNT(DISTINCT A.Brand) AS QtyBrands 	FROM [Inventory_TuckerRocky_ItemMaster_New] AS A WITH (NOLOCK) LEFT JOIN [vsql4\instance4].[Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 185 and B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND A.Brand NOT IN('FUELL','UBCO','Vertex','New Rage Cycles','Lextek Exhaust','FI2000','Airhead','CP-Carrillo','Strider','Pathfinder L.E.D.','Sargent Cycle','INNORACK','BackOff','Cardo','GUP','Sport Chrome','San Diego Customs','Bahn')) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Tire Depot Co.' AS Vendor,QtyBrands  FROM (SELECT 389 AS VendorId, COUNT(DISTINCT A.brand) AS QtyBrands FROM Inventory_TireDepot AS A WITH (NOLOCK) LEFT JOIN [vsql4\instance4].[Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 389 and B.VendorBrandName = A.brand WHERE B.ID IS NULL AND A.brand NOT IN('TUBE & SOLID','IMPORT','WHEELS','WHEEL ONE','EFX TIRES','OTHER','ACCESORIES','RM','STEELMASTER','MKW','AKUZA WHEELS','SCORPION WHEELS','HEAVY HITTER','LONGTRAXX','GRAND PRIX','VOLUME REBATES','PATHFINDER','SRW','DAKAR','VALVE','IMPORT WHEELS','RECAPS','TRANSEAGLE','CHAPMAN','LION SPORT','MARK MA','PERCHERON','BLEMED','HOSOON')) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Tire Depot Co.-DS' AS Vendor,QtyBrands  FROM (SELECT 405 AS VendorId, COUNT(DISTINCT A.brand) AS QtyBrands FROM Inventory_TireDepot_2 AS A WITH (NOLOCK) LEFT JOIN [vsql4\instance4].[Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 405 and B.VendorBrandName = A.brand WHERE B.ID IS NULL AND A.Brand NOT IN ('OTR','TransEagle','Wild Country')) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Marr Bros., Inc.' AS Vendor,QtyBrands  FROM (SELECT 384 AS VendorId, COUNT(DISTINCT A.PriceSheetBrand) AS QtyBrands 	FROM Inventory_MarrBros AS A WITH (NOLOCK) LEFT JOIN [vsql4\instance4].[Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK)ON B.Vendorid = 384 and B.VendorBrandName = A.PriceSheetBrand WHERE B.ID IS NULL AND A.PriceSheetBrand NOT IN ('NGNGK SPARKPLUGS','KNK&N FILTERS','MBTECH SCHOOLS','MBAMER LUBRICATIN','CPRIDER TOPS','MB283-SHADES','STCOUNTRY HM PROD','ESESA FORM MATERI','MBNITRILE GLOVES','TETEC REG PARTS','KOTEC REG PARTS','MUTEC REG PARTS','MBREADER BULB-140','MBFACE MASKS','ESESA FORM MATERI','GRESA FORM MATERI','EAESA FORM MATERI','ZANGK SPARKPLUGS','MBIGN ANALYZER','MBGLOVES')) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Hanson' AS Vendor,QtyBrands  FROM (SELECT 222 AS VendorId, COUNT(DISTINCT A.linecode) AS QtyBrands 	FROM Inventory_Hanson AS A WITH (NOLOCK)LEFT JOIN [vsql4\instance4].[Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK)ON B.Vendorid = 222 and B.VendorManCode = A.linecode WHERE B.ID IS NULL AND A.LineCode NOT IN('APW','DCB','RQ','SG')) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Meyer-DS' AS Vendor,QtyBrands  FROM (SELECT 233 AS VendorId, COUNT(DISTINCT LEFT(A.VendorPartNumber, 3)) AS QtyBrands 	FROM Inventory_meyer AS A WITH (NOLOCK) LEFT JOIN [vsql4\instance4].[Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 233 and B.VendorManCode = LEFT(A.VendorPartNumber, 3) WHERE B.ID IS NULL GROUP BY LEFT(A.VendorPartNumber, 3) HAVING SUM(CASE WHEN A.MfgQTY > 0 THEN 1 ELSE 0 END)  > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Automatic Distributing' AS Vendor,QtyBrands  FROM (SELECT 197 AS VendorId, COUNT(DISTINCT B.Brand) AS QtyBrands FROM Inventory_AutoDist_ItemMaster AS A WITH (NOLOCK) JOIN Inventory_AutoDist AS B WITH (NOLOCK) ON B.Brand = A.Manufacturer LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS C WITH (NOLOCK) ON C.Vendorid = 197 and C.VendorBrandName = B.Brand WHERE C.ID IS NULL ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 380 AS VendorId,'Arnold Motor Supply' AS Vendor, QtyBrands FROM (SELECT 380 AS VendorId, COUNT(DISTINCT A.Line) AS QtyBrands FROM [vsql4\instance4].vendordata.[dbo].Inventory_TheArnoldGroup AS A WITH (NOLOCK) LEFT JOIN [vsql4\instance4].[Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 380 AND B.VendorManCode = A.Line  WHERE B.Id IS NULL AND A.Line NOT IN ('CUR','PCC','SKY','SPC','PLY','FON','RHD','RTI','OAK','PLN','UTD','PBE','EMM','TMC','XIM','XWS','PIT','POL','TOW','RYP','DMA','RSC','MED','ICE','CUS','NOR','XCH','PFM','PMC','MAN')) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 394 AS VendorId,'OE Wheel Distributors' AS Vendor,QtyBrands FROM (SELECT 197 AS VendorId, COUNT(DISTINCT A.Brand) AS QtyBrands FROM DEN_OEWheel_MasterData AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 394 and B.VendorBrandName = A.Brand WHERE B.ID IS NULL ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'National Performance Warehouse' AS Vendor,QtyBrands  FROM (SELECT 100 AS VendorId, COUNT(DISTINCT A.Line_code) AS QtyBrands FROM Inventory_SpeedWarehouseNPW AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 100 and B.VendorManCode = A.Line_code WHERE B.ID IS NULL AND A.Line_code NOT IN( 'SPY','RGG','XW5','PSP','QPS','SGG','UQA','SI9','UCH','BUR','ASG','VAN','CPS','TCP','GWT','PRC','DDR','ANA','GGA','MSC','POM','DSC','PEE','ENK','PAC','PAS','BAN','AXP','ZOO','USC','BLC','STL','PCA','USW','OMX','PMU','RMP','AAP','HTO','SHX','WOO','PBX','CWC','TMS','TO3','PMZ','BPO','SUX','TNR','ESP','TOM','MSL','TTT','AFC','HIP','HRT','SPC','PWF','CIA','BAD','ANE','HOI','NPR','MKA','REW','PIM','SOW','LPS','GRV','TRS','WEC','USR','ELM','PRL','CHS','TSP','NAO','AVE','NEB','OVR','TRG','RVL','DNA','PBV','PLP','ABO','PTL','PTT','GEE','OIL','ELA','CBR','BIF','PLS','XEA','WWP','','PMV','WWF','MAP','AMT','VIJ','TIG','GAS','FRI','ANI','PDI','NAP','AEP','OWE','PEP','INA','BUG','DPW','EPC','PSN','COO','REL','CRE','MAI','SLL','IMC','GBS','INM','ADE','PBA','PVC','BHC','THX','CTT','OAK','KMI','AME','LMI','LUV','AUP','RBP','MGR','XWS','BIM','CNK','ELE','FOL','GTT','IPP','JTI','MOL','RAA','RDR','RUD','SPP','SXP','XPB','ARI','AXO','BRO','BSI','CHM','COB','CSB','DRA','FLP','LAB','LPC','MWI','PGG','PNZ','QSH','QUA')) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'The Hoffman Group' AS Vendor,QtyBrands  FROM (SELECT 118 AS VendorId, COUNT(DISTINCT A.Brand) AS QtyBrands FROM Inventory_TheHoffmanGroup AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 118 and B.VendorBrandName = A.Brand WHERE B.ID IS NULL ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Parts Authority - DS' AS Vendor,QtyBrands  FROM (SELECT 180 AS VendorId, COUNT(DISTINCT A.Brand_Name) AS QtyBrands FROM Inventory_PartsAuthority AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 180 and B.VendorBrandName = A.Brand_Name WHERE B.ID IS NULL GROUP BY A.Brand_Name HAVING SUM(CASE WHEN A.VendorStock > 0 THEN 1 ELSE 0 END)  > 0 ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Medart Inc' AS Vendor,QtyBrands  FROM (SELECT 290 AS VendorId, COUNT(DISTINCT A.MFGCode) AS QtyBrands FROM Inventory_Medart_Part AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 290 and B.VendorManCode = A.MFGCode WHERE B.ID IS NULL ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Skyjacker' AS Vendor,QtyBrands  FROM (SELECT 328 AS VendorId, COUNT(DISTINCT LEFT(A.SKU,2)) AS QtyBrands FROM Inventory_Skyjacker AS A WITH (NOLOCK)LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 328 and B.VendorManCode = LEFT(A.SKU,2) WHERE B.ID IS NULL ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Westin' AS Vendor,QtyBrands  FROM (SELECT 330 AS VendorId, COUNT(DISTINCT B.brand) AS QtyBrands FROM Inventory_Westin AS A WITH (NOLOCK) JOIN [vsql2\instance2].[PriceSheet].dbo.Gena_Westin043021 AS B WITH (NOLOCK) ON B.MPN = A.MPN  LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS C WITH (NOLOCK) ON C.Vendorid = 330 AND C.VendorBrandName = B.braND WHERE C.ID IS NULL ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 71 AS VendorId,'Megan Racing' AS Vendor,NULL AS QtyBrands
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'U.S. AutoForce' AS Vendor,QtyBrands  FROM (SELECT 383 AS VendorId, COUNT(DISTINCT A.Code) AS QtyBrands FROM Inventory_USAutoForce AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 383 AND B.VendorManCode = A.Code WHERE B.ID IS NULL ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'LKQ' AS Vendor,QtyBrands  FROM (SELECT 318 AS VendorId, COUNT(DISTINCT A.ProductLine) AS QtyBrands FROM Inventory_LKQ AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 318 AND B.VendorManCode = A.ProductLine WHERE B.ID IS NULL ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Mishimoto' AS Vendor,QtyBrands  FROM (SELECT 322 AS VendorId, COUNT(DISTINCT LEFT(A.MPN,3)) AS QtyBrands FROM Inventory_Mishimoto AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 322 AND B.VendorManCode = LEFT(A.MPN,3) WHERE B.ID IS NULL ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Donovan Marine' AS Vendor,QtyBrands  FROM (SELECT 287 AS VendorId, COUNT(DISTINCT LEFT(A.MPN,3)) AS QtyBrands FROM Inventory_DonovanNew AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 287 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND A.QTY > 0 ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Go Rhino' AS Vendor,QtyBrands  FROM (SELECT 332 AS VendorId, COUNT(DISTINCT LEFT(A.MPN,3)) AS QtyBrands FROM Inventory_GoRhino AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 332 AND B.VendorBrandName = A.Name WHERE B.ID IS NULL AND A.QTY > 0 AND A.MPN IS NOT NULL ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 362 AS VendorId,'Unity Automotive' AS Vendor,NULL AS QtyBrands  --FROM (SELECT 362 AS VendorId, COUNT(DISTINCT LEFT(A.MPN,3)) AS QtyBrands FROM Inventory_Unity AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 362 AND B.VendorBrandName = A.Name WHERE B.ID IS NULL AND A.QTY > 0 AND A.MPN IS NOT NULL ) AS A GROUP BY VendorId,QtyBrands;
--INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
--SELECT VendorId,'Tire Web LLC' AS Vendor,QtyBrands  FROM (SELECT 385 AS VendorId, COUNT(DISTINCT A.Brand) AS QtyBrands FROM Inventory_TireWeb AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 385 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND A.QTY > 0 AND ISNULL(A.MPN,'') <> '' AND ISNULL(A.QTY,0) > 0  ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'The Wheel Group' AS Vendor,QtyBrands  FROM (SELECT 377 AS VendorId, COUNT(DISTINCT A.Brand) AS QtyBrands FROM Inventory_TheWheelGroup AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 377 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'') <> ''  AND A.QTY > 0 ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Diode Dynamics' AS Vendor,QtyBrands  FROM (SELECT 350 AS VendorId, COUNT(DISTINCT LEFT(A.MPN,3)) AS QtyBrands FROM Inventory_DiodeDynamics AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 350 AND B.VendorManCode = LEFT(A.MPN,3) WHERE B.ID IS NULL  ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 369 AS VendorId,'Borgeson Universal' AS Vendor,NULL AS QtyBrands -- FROM (SELECT 369 AS VendorId, COUNT(DISTINCT LEFT(A.MPN,3)) AS QtyBrands FROM Inventory_Borgeson AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 369 AND B.VendorManCode = LEFT(A.MPN,3) WHERE B.ID IS NULL  ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT  VendorId,'Black Horse Off Road' AS Vendor, QtyBrands  FROM (SELECT 365 AS VendorId, COUNT(DISTINCT A.LineCode) AS QtyBrands FROM Inventory_BlackHorse AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 365 AND B.VendorManCode = A.LineCode WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 335 AS VendorId,'Fairchild Industries' AS Vendor,NULL AS QtyBrands  --FROM (SELECT 335 AS VendorId, COUNT(DISTINCT A.LineCode) AS QtyBrands FROM Inventory_BlackHorse AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 335 AND B.VendorManCode = A.LineCode WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Partslink' AS Vendor, QtyBrands FROM (SELECT 319 AS VendorId, COUNT(DISTINCT A.Brand) AS QtyBrands FROM Inventory_PartsLink AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 319 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Neuco Inc.' AS Vendor, QtyBrands FROM (SELECT 391 AS VendorId, COUNT(DISTINCT A.Brand) AS QtyBrands FROM Inventory_Neuco AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 391 AND B.VendorManCode = A.Line WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Overland Vehicle Systems' AS Vendor, QtyBrands FROM (SELECT 337 AS VendorId, COUNT(DISTINCT A.Brand) AS QtyBrands FROM Inventory_OVS AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 337 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.Brand,'''') <> '''' AND ISNULL(A.QTY,0) > 0  ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 324 AS VendorId,'Steelcraft' AS Vendor, NULL AS QtyBrands-- FROM (SELECT 324 AS VendorId, COUNT(DISTINCT A.Brand) AS QtyBrands FROM Inventory_Steelcraft AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 324 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.Brand,'''') <> '''' AND ISNULL(A.QTY,0) > 0  ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Wholesale Tire Distributors' AS Vendor, QtyBrands FROM (SELECT 376 AS VendorId, COUNT(DISTINCT A.Brand) AS QtyBrands FROM Inventory_WhosaleTireDistribution AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 376 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.Brand,'''') <> '''' AND ISNULL(A.QTY,0) > 0  ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Turbo Wholesale Tires' AS Vendor, QtyBrands FROM (SELECT 304 AS VendorId, COUNT(DISTINCT A.Make) AS QtyBrands FROM Inventory_TurboTireNew AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 304 AND B.VendorBrandName = A.Make WHERE B.ID IS NULL AND ISNULL(A.Make,'''') <> '''' AND ISNULL(A.Stock,0) > 0  ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'I3 Enterprise Inc.' AS Vendor, QtyBrands FROM (SELECT 346 AS VendorId, COUNT(DISTINCT A.BrandName) AS QtyBrands FROM Inventory_I3 AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 346 AND B.VendorBrandName = A.BrandName WHERE B.ID IS NULL AND ISNULL(A.BrandName,'''') <> '''' AND ISNULL(A.QTY,0) > 0  ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 89 AS VendorId,'EGR' AS Vendor, NULL AS QtyBrands --FROM (SELECT 89 AS VendorId, COUNT(DISTINCT A.BrandName) AS QtyBrands FROM Inventory_I3 AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 89 AND B.VendorBrandName = A.BrandName WHERE B.ID IS NULL AND ISNULL(A.BrandName,'''') <> '''' AND ISNULL(A.QTY,0) > 0  ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 359 AS VendorId,'Westar Distribution' AS Vendor, NULL AS QtyBrands --FROM (SELECT 359 AS VendorId, COUNT(DISTINCT A.BrandName) AS QtyBrands FROM Inventory_I3 AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 359 AND B.VendorBrandName = A.BrandName WHERE B.ID IS NULL AND ISNULL(A.BrandName,'''') <> '''' AND ISNULL(A.QTY,0) > 0  ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'DV8 Off-Road' AS Vendor, QtyBrands FROM (SELECT 359 AS VendorId, COUNT(DISTINCT A.LineCode) AS QtyBrands FROM Inventory_DV8 AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 359 AND B.VendorManCode = A.LineCode WHERE B.ID IS NULL AND ISNULL(A.LineCode,'''') <> '''' AND ISNULL(A.QTY,0) > 0  ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 317 AS VendorId,'Spec-D Tuning' AS Vendor, NULL AS QtyBrands --FROM (SELECT 317 AS VendorId, COUNT(DISTINCT A.LineCode) AS QtyBrands FROM Inventory_SpecDNEW AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 317 AND B.VendorManCode = A.LineCode WHERE B.ID IS NULL AND ISNULL(A.LineCode,'''') <> '''' AND ISNULL(A.QTY,0) > 0  ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 352 AS VendorId,'Pittman Outdoors' AS Vendor, NULL AS QtyBrands --FROM (SELECT 352 AS VendorId, COUNT(DISTINCT A.LineCode) AS QtyBrands FROM Inventory_SpecDNEW AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 352 AND B.VendorManCode = A.LineCode WHERE B.ID IS NULL AND ISNULL(A.LineCode,'''') <> '''' AND ISNULL(A.QTY,0) > 0  ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'AlloyGator' AS Vendor, QtyBrands FROM (SELECT 348 AS VendorId, COUNT(DISTINCT A.Brand) AS QtyBrands FROM Inventory_AlloyGator AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 348 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.Brand,'''') <> '''' AND ISNULL(A.QTY,0) > 0  ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Thule' AS Vendor, QtyBrands FROM (SELECT 329 AS VendorId, COUNT(DISTINCT A.Brand) AS QtyBrands FROM Inventory_Thule AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 329 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.Brand,'''') <> '''' AND ISNULL(A.Quantity,0) > 0  ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Classic Accessories' AS Vendor, QtyBrands FROM (SELECT 360 AS VendorId, COUNT(DISTINCT A.Brand) AS QtyBrands FROM Inventory_ClassicAccessories AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 360 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT  340 AS VendorId,'Gibson' AS Vendor, NULL AS QtyBrands --FROM (SELECT 340 AS VendorId, COUNT(DISTINCT A.Brand) AS QtyBrands FROM Inventory_ClassicAccessories AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 340 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT  VendorId,'Holley Performance Products' AS Vendor, QtyBrands FROM (SELECT 161 AS VendorId, COUNT(DISTINCT A.Brand) AS QtyBrands FROM Inventory_Holleynew AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 161 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT  54 AS VendorId,'Corbeau' AS Vendor, NULL AS QtyBrands --FROM (SELECT 54 AS VendorId, COUNT(DISTINCT A.Brand) AS QtyBrands FROM Inventory_Holleynew AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 54 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT  166 AS VendorId,'Borla' AS Vendor, NULL AS QtyBrands --FROM (SELECT 54 AS VendorId, COUNT(DISTINCT A.Brand) AS QtyBrands FROM Inventory_Holleynew AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B v ON B.Vendorid = 166 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT  VendorId,'APS' AS Vendor, QtyBrands FROM (SELECT 345 AS VendorId, COUNT(DISTINCT LEFT(A.MPN,2)) AS QtyBrands FROM Inventory_APS AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 345 AND B.VendorManCode = LEFT(A.MPN,2)WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 152 AS VendorId,'Seibon Carbon' AS Vendor, NULL AS QtyBrands --FROM (SELECT 152 AS VendorId, COUNT(DISTINCT LEFT(A.MPN,2)) AS QtyBrands FROM Inventory_APS AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 152 AND B.VendorManCode = LEFT(A.MPN,2)WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Front Runner Outfitters' AS Vendor, QtyBrands FROM (SELECT 347 AS VendorId, COUNT(DISTINCT LEFT(A.MPN,3)) AS QtyBrands FROM Inventory_FrontRunner AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 347 AND B.VendorManCode = LEFT(A.MPN,3)WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 327 AS VendorId,'Covercraft' AS Vendor, NULL AS QtyBrands --FROM (SELECT 327 AS VendorId, COUNT(DISTINCT LEFT(A.MPN,3)) AS QtyBrands FROM Inventory_Covercraft AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 327 AND B.VendorManCode = LEFT(A.MPN,3)WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 303 AS VendorId,'Brake Parts' AS Vendor, NULL AS QtyBrands --FROM (SELECT 303 AS VendorId, COUNT(DISTINCT LEFT(A.MPN,3)) AS QtyBrands FROM Inventory_Covercraft AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 303 AND B.VendorManCode = LEFT(A.MPN,3)WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Wingate Tires' AS Vendor, QtyBrands FROM (SELECT 388 AS VendorId, COUNT(DISTINCT A.Brand ) AS QtyBrands FROM Inventory_WingateTire AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 388 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 381 AS VendorId,'Paramount Automotive' AS Vendor, NULL AS QtyBrands --FROM (SELECT 381 AS VendorId, COUNT(DISTINCT A.Brand ) AS QtyBrands FROM Inventory_ParamountAutomotive AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 381 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 338 AS VendorId,'Intro-Tech' AS Vendor, NULL AS QtyBrands --FROM (SELECT 338 AS VendorId, COUNT(DISTINCT A.Brand ) AS QtyBrands FROM Inventory_WingateTire AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 338 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 33 AS VendorId,'KSport' AS Vendor, NULL AS QtyBrands --FROM (SELECT 33 AS VendorId, COUNT(DISTINCT A.Brand ) AS QtyBrands FROM Inventory_WingateTire AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 33 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 104 AS VendorId,'BBK Performance' AS Vendor, NULL AS QtyBrands --FROM (SELECT 104 AS VendorId, COUNT(DISTINCT A.Brand ) AS QtyBrands FROM Inventory_WingateTire AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 104 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 325 AS VendorId,'Dash Designs' AS Vendor, NULL AS QtyBrands --FROM (SELECT 325 AS VendorId, COUNT(DISTINCT A.Brand ) AS QtyBrands FROM Inventory_WingateTire AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 325 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'Fia Inc.' AS Vendor, QtyBrands FROM (SELECT 398 AS VendorId, COUNT(DISTINCT LEFT(A.MPN,2) ) AS QtyBrands FROM Inventory_FIA AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 398 AND B.VendorManCode = LEFT(A.MPN,2) WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'NRG Innovations' AS Vendor, QtyBrands FROM (SELECT 371 AS VendorId, COUNT(DISTINCT LEFT(A.MPN,2) ) AS QtyBrands FROM Inventory_nrg AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 371 AND B.VendorBrandName = LEFT(A.MPN,2) WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,'''') <> 'NO' ) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT VendorId,'FORTLUFT INC' AS Vendor, QtyBrands FROM (SELECT 368 AS VendorId, COUNT(DISTINCT A.Brand ) AS QtyBrands FROM Inventory_FortLuft AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 368 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 366 AS VendorId,'bROK Products LLC' AS Vendor, NULL AS QtyBrands --FROM (SELECT 366 AS VendorId, COUNT(DISTINCT A.Brand ) AS QtyBrands FROM Inventory_WingateTire AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 366 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 364 AS VendorId,'BA-TENTS' AS Vendor, NULL AS QtyBrands --FROM (SELECT 364 AS VendorId, COUNT(DISTINCT A.Brand ) AS QtyBrands FROM Inventory_BaTents AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 364 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 344 AS VendorId,'DU-HA' AS Vendor, NULL AS QtyBrands --FROM (SELECT 344 AS VendorId, COUNT(DISTINCT A.Brand ) AS QtyBrands FROM Inventory_dUhA AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 344 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 156 AS VendorId,'Addictive Desert Designs' AS Vendor, NULL AS QtyBrands --FROM (SELECT 156 AS VendorId, COUNT(DISTINCT A.Brand ) AS QtyBrands FROM Inventory_ADD AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 156 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 163 AS VendorId,'Stance' AS Vendor, NULL AS QtyBrands --FROM (SELECT 163 AS VendorId, COUNT(DISTINCT A.Brand ) AS QtyBrands FROM Inventory_ADD AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 163 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 203 AS VendorId,'Girodisc Racing Brakes' AS Vendor, NULL AS QtyBrands --FROM (SELECT 203 AS VendorId, COUNT(DISTINCT A.Brand ) AS QtyBrands FROM Inventory_ADD AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 203 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 357 AS VendorId,'MGP Caliper Covers' AS Vendor, NULL AS QtyBrands --FROM (SELECT 357 AS VendorId, COUNT(DISTINCT A.Brand ) AS QtyBrands FROM Inventory_MGP AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 357 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 353 AS VendorId,'Romik' AS Vendor, NULL AS QtyBrands --FROM (SELECT 353 AS VendorId, COUNT(DISTINCT A.Brand ) AS QtyBrands FROM Inventory_Romik AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 353 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
INSERT INTO #20FirstBrands (VendorId,Vendor,QtyBrands)
SELECT 372 AS VendorId,'Bubba Rope' AS Vendor, NULL AS QtyBrands --FROM (SELECT 372 AS VendorId, COUNT(DISTINCT A.Brand ) AS QtyBrands FROM Inventory_BubbaRope AS A WITH (NOLOCK) LEFT JOIN [Autoplicity].[dbo].[PriceSheet] AS B WITH (NOLOCK) ON B.Vendorid = 372 AND B.VendorBrandName = A.Brand WHERE B.ID IS NULL AND ISNULL(A.MPN,'''') <> '''' AND ISNULL(A.QTY,0) > 0  AND  A.Qty > 0) AS A GROUP BY VendorId,QtyBrands;
;																	


SELECT A.VendorId
	  ,MAX(A.vendor) AS VendorName
	  ,COUNT(*) AS QtyOFOrders
	  ,B.QtyBrands
	  ,CASE WHEN A.Vendor = 'Meyer Distributing' THEN 'Need brand name'
				WHEN A.Vendor = 'FMPco' THEN 'Need brand name'
				WHEN A.Vendor = 'ORS Nasco' THEN 'Need brand name'  
				WHEN A.Vendor = 'OE Wheel Distributors' THEN 'Need brand name'
				WHEN A.Vendor = 'Megan Racing' THEN 'Need brand name' 
				WHEN A.Vendor = 'Unity Automotive' THEN 'Need brand name'
				WHEN A.Vendor = 'Borgeson Universal' THEN 'Need brand name'
				WHEN A.Vendor = 'Fairchild Industries' THEN 'Need brand name'
				WHEN A.Vendor = 'Borgeson Universal' THEN 'Need brand name'
				WHEN A.Vendor = 'Steelcraft' THEN 'Need brand name'
				WHEN A.Vendor = 'EGR' THEN 'Need brand name'
				WHEN A.Vendor = 'Westar Distribution' THEN 'Need brand name'
				WHEN A.Vendor = 'Spec-D Tuning' THEN 'Need brand name'
				WHEN A.Vendor = 'Gibson' THEN 'Need brand name'
				WHEN A.Vendor = 'Corbeau' THEN 'Need Inventory_File'
				WHEN A.Vendor = 'Borla' THEN 'Need brand name'
				WHEN A.Vendor = 'Seibon Carbon' THEN 'Need brand name'
				WHEN A.Vendor = 'Covercraft' THEN 'Need brand name'
				WHEN A.Vendor = 'Brake Parts' THEN 'Need brand name'
				WHEN A.Vendor = 'Paramount Automotive' THEN 'Need brand name'
				WHEN A.Vendor = 'Intro-Tech' THEN 'Need Inventory_File'
				WHEN A.Vendor = 'KSport' THEN 'Need Inventory_File'
				WHEN A.Vendor = 'BBK Performance' THEN 'Need Inventory_File'
				WHEN A.Vendor = 'Dash Designs' THEN 'Need Inventory_File'
				WHEN A.Vendor = 'NRG Innovations' THEN 'Need brand name'
				WHEN A.Vendor = 'bROK Products LLC' THEN 'Need brand name'
				WHEN A.Vendor = 'BA-TENTS' THEN 'Need brand name'
				WHEN A.Vendor = 'DU-HA' THEN 'Need brand name'
				WHEN A.Vendor = 'Addictive Desert Designs' THEN 'Need brand name'
				WHEN A.Vendor = 'Stance' THEN 'Need Inventory_File'
				WHEN A.Vendor = 'Girodisc Racing Brakes' THEN 'Need Inventory_File'
				WHEN A.Vendor = 'MGP Caliper Covers' THEN 'Need brand name'
				WHEN A.Vendor = 'Romik' THEN 'Need brand name'
				WHEN A.Vendor = 'Bubba Rope' THEN 'Need brand name'
				WHEN A.Vendor = 'XL Parts' THEN 'Need brand name'
				WHEN A.Vendor = 'The Parts House' THEN 'Need brand name'
				WHEN A.Vendor = 'Competition Specialties' THEN 'Need brand name'
				WHEN A.Vendor = '3D MAXpider' THEN 'Need brand name'
				ELSE '-' END AS [Note]
FROM 
(
	SELECT VendorId,OrderDate,Vendor 
	FROM [vsql3\instance3].[CRmAPTools].dbo.VW_OrderItemsWithPOs
) AS A
JOIN #20FirstBrands AS B ON B.VendorId = A.VendorId
WHERE A.OrderDate >= '2023-01-01' AND A.VendorId IS NOT NULL AND A.VendorId <> 295
GROUP BY A.vendorId,B.QtyBrands,A.Vendor
ORDER BY QtyOFOrders DESC;


DROP TABLE #20FirstBrands;

